#!/bin/bash

echo "🤖 hello!"

echo "🤖 removing old build files"
rm -rf build/

echo "🤖 transpiling files"
./node_modules/.bin/babel src --out-dir build --presets=@babel/env

echo "🤖 copying non js files"
rsync -av --progress src/ build/ --exclude js

# echo "🤖 adding cache buster to urls"
# python3 addcb.py

echo "🤖 bye!"
